name: CI

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: debian:10

    steps:
      - uses: actions/checkout@v3

      - name: Update system
        run: |
          sed 's/^deb /deb-src /' /etc/apt/sources.list >>/etc/apt/sources.list
          apt-get update
          apt-get full-upgrade -y

      - name: Install dependencies
        run: |
          apt-get install -y build-essential
          apt-get build-dep -y linux

      - name: Download kernel
        run: |
          apt-get source linux

      - name: Build kernel
        run: |
          cd linux-*
          echo $nproc
          export MAKEFLAGS=-j$(nproc)
          debian/bin/test-patches
